# Import the relevant libraries

In [1]:
import numpy as np

# Declaring scalars, vectors, and matrices

## Scalars

In [2]:
s = 5

In [3]:
s

5

## Vectors

In [4]:
v = np.array([5,-2,4])

In [5]:
v

array([ 5, -2,  4])

## Matrices

In [6]:
m = np.array([[5,12,6],[-3,0,14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data types

In [8]:
type(s)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

In [11]:
s_array = np.array([5])

In [12]:
type(s_array)

numpy.ndarray

## Data shapes

In [13]:
m.shape

(2, 3)

In [14]:
v.shape

(3,)

In [ ]:
s.shape

In [ ]:
s_array.shape

## Creating a column vector

In [15]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [16]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [17]:
m+s

array([[10, 17, 11],
       [ 2,  5, 19]])

In [18]:
m+s_array

array([[10, 17, 11],
       [ 2,  5, 19]])

In [19]:
v+s

array([10,  3,  9])

In [20]:
v

array([ 5, -2,  4])

In [21]:
v+s_array

array([10,  3,  9])

In [22]:
m+v

array([[10, 10, 10],
       [ 2, -2, 18]])